VC140_ON_VS2017:            # [win]
  - "1"                     # [win]
c_compiler:                 # [win]
  - c3i_test2::vs2015       # [win]
cxx_compiler:               # [win]
  - c3i_test2::vs2015       # [win]
python:                     # [win]
  - 3.7                     # [win]
vc:                         # [win]
  - 14                      # [win]