c_compiler:     # [win]
  - vs2008      # [win]
  - vs2015      # [win]
  - vs2017      # [win]

cxx_compiler:     # [win]
  - vs2008        # [win]
  - vs2015        # [win]
  - vs2017        # [win]

vc:                    # [win]
  - 9                  # [win]
  - 14                 # [win]
  - 14.1               # [win]

python:
  - 2.7
  - 3.6
  - 2.8

