c_compiler:                 # [win]
  - vs2015       # [win]
cxx_compiler:               # [win]
  - vs2015       # [win]
python:                     # [win]
  - 3.7                     # [win]
vc:                         # [win]
  - 14                      # [win]

channel_sources:                    # [win]
- c3i_test2,conda-forge,defaults    # [win]
