{% set version = "0.19.0" %}

package:
  name: thrift-split
  version: {{ version }}

source:
  - url: http://archive.apache.org/dist/thrift/{{ version }}/thrift-{{ version }}.tar.gz
    sha256: d49c896c2724a78701e05cfccf6cf70b5db312d82a17efe951b441d300ccf275
    patches:
      - patches/0001-windows-fixes.patch                             # [win]
      - patches/0002-Add-boost-throw_exception-implementation.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
  ignore_run_exports_from:
    # we only need the binaries at build-time
    - winflexbison

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - pkg-config
    - bison           # [unix]
    - flex            # [unix]
    - winflexbison    # [win]
  host:
    - boost-cpp
    - libevent
    - openssl
    - zlib
  run:

outputs:
  - name: libthrift
    script: install.sh   # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja
      host:
        - boost-cpp
        - libevent
        - openssl
        - zlib
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - pkg-config
        # find_package(thrift) really wants to find zlib
        - zlib  # [win]
      files:
        - cmake_test/
      commands:
        {% for each in ["thrift", "thriftnb", "thriftz"] %}
        # presence of shared libs
        - test -f $PREFIX/lib/lib{{ each }}.so                  # [linux]
        - test -f $PREFIX/lib/lib{{ each }}.dylib               # [osx]
        - if not exist %LIBRARY_LIB%\{{ each }}md.lib exit 1    # [win]
        - if not exist %LIBRARY_BIN%\{{ each }}md.dll exit 1    # [win]

        # absence of static libs
        - test ! -f $PREFIX/lib/lib{{ each }}.a                 # [unix]
        {% endfor %}

        # absence of binaries
        - test ! -f $PREFIX/bin/thrift                          # [unix]
        - if exist %LIBRARY_BIN%\thrift.exe exit 1              # [win]

        # presence of headers
        - test -f $PREFIX/include/thrift/Thrift.h               # [unix]
        - if not exist %LIBRARY_INC%\thrift\Thrift.h exit 1     # [win]

        # pkg-config metadata (different naming than DSOs; uses hyphen, no "lib" prefix)
        {% for each in ["thrift", "thrift-nb", "thrift-z"] %}
        - pkg-config --print-errors --exact-version "{{ version }}" {{ each }}
        {% endfor %}

        # test CMake integration, i.e. find_package(thrift)
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS .   # [unix]
        - cmake -GNinja %CMAKE_ARGS% .  # [win]

  - name: thrift-compiler
    script: install.sh   # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - boost-cpp
        - libevent
        - openssl
        - zlib
      run:
        - {{ pin_subpackage("libthrift", exact=true) }}
    test:
      commands:
        # presence of binaries
        - test -f $PREFIX/bin/thrift                    # [unix]
        - if not exist %LIBRARY_BIN%\thrift.exe exit 1  # [win]

  - name: thrift-cpp
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      host:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - {{ pin_subpackage("thrift-compiler", exact=true) }}
      run:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - {{ pin_subpackage("thrift-compiler", exact=true) }}
    test:
      commands:
        - echo "tested in other outputs"

about:
  home: http://thrift.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: >-
    Compiler and C++ libraries and headers for the Apache Thrift RPC system
  dev_url: https://github.com/apache/thrift

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
    - h-vetinari
  feedstock-name: thrift-cpp
