# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: vs2017_win2016
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 240
  strategy:
    maxParallel: 4
    matrix:
      win_c_compilervs2008cxx_compilervs2008:
        CONFIG: win_c_compilervs2008cxx_compilervs2008
        CONDA_BLD_PATH: D:\\bld\\
        UPLOAD_PACKAGES: False
  steps:

    - script: |
        choco install visualcplusplusexpress2008 vcpython27 -fdv -y --debug
      condition: contains(variables['CONFIG'], 'vs2008')
      displayName: Install vcpython27.msi

    - powershell: |
        Set-PSDebug -Trace 1

        $batchcontent = @"
        ECHO ON
        SET vcpython=C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0

        DIR "%vcpython%"

        CALL "%vcpython%\vcvarsall.bat" %*
        "@

        $batchDir = "C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC"
        $batchPath = "$batchDir" + "\vcvarsall.bat"
        New-Item -Path $batchPath -ItemType "file" -Force

        Set-Content -Value $batchcontent -Path $batchPath
        Get-ChildItem -Path $batchDir
        Get-ChildItem -Path ($batchDir + '\..')
      displayName: Patch VC9

    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    # Generate conda-forge build environment
    - script: |
        CALL activate base
        conda install conda-build conda conda-forge::conda-forge-ci-setup -c conda-forge
      displayName: Install conda-build and activate environment
      failOnStderr: false

    - script: |
        CALL activate base
        setup_conda_rc .\ .\recipe .\.ci_support\%CONFIG%.yaml
      displayName: Update conda configs for current config
    - script: |
        CALL activate base
        run_conda_forge_build_setup
      displayName: run_conda_forge_build_setup

    - script: |
        CALL activate base
        conda update --all
      displayName: conda update --all

    - script: |
        rmdir C:\strawberry /s /q
      continueOnError: true
      displayName: remove strawberryperl

    - script: |
        CALL activate base
        conda.exe build recipe -m .ci_support\%CONFIG%.yaml
      displayName: Build recipe
      failOnStderr: false
      env:
        
        # Since we have a non-standard fake VC9 install set this override
        VS90COMNTOOLS: "C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\bin"
        
        PYTHONUNBUFFERED: 1

    - script: |
        upload_package .\ .\recipe .ci_support\%CONFIG%.yaml
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      condition: not(eq(variables['UPLOAD_PACKAGES'], 'False'))


- job: vs2015_win2012r2
  pool:
    vmImage: vs2015-win2012r2
  timeoutInMinutes: 240
  strategy:
    maxParallel: 4
    matrix:
      win_c_compilervs2015cxx_compilervs2015:
        CONFIG: win_c_compilervs2015cxx_compilervs2015
        CONDA_BLD_PATH: D:\\bld\\
        UPLOAD_PACKAGES: False
  steps:

    # Set up conda since the vs2015 does not have a miniconda installation
    - script: |
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
      displayName: Install choco

    - powershell: |
        Write-Host "##vso[task.prependpath]C:\ProgramData\chocolatey\bin"
        Write-Host "##vso[task.setvariable variable=CONDA]D:\Miniconda3\"
      displayName: Add choco to PATH, and conda env var

    - script: |
        ECHO ON
        choco install miniconda3 --params="'/D=D:\Miniconda3 /InstallationType=AllUsers'" --yes
      displayName: Install miniconda3

    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    # Generate conda-forge build environment
    - script: |
        CALL activate base
        conda install conda-build conda conda-forge::conda-forge-ci-setup -c conda-forge
      displayName: Install conda-build and activate environment
      failOnStderr: false

    - script: |
        CALL activate base
        setup_conda_rc .\ .\recipe .\.ci_support\%CONFIG%.yaml
      displayName: Update conda configs for current config
    - script: |
        CALL activate base
        run_conda_forge_build_setup
      displayName: run_conda_forge_build_setup

    - script: |
        CALL activate base
        conda update --all
      displayName: conda update --all

    - script: |
        rmdir C:\strawberry /s /q
      continueOnError: true
      displayName: remove strawberryperl

    - script: |
        CALL activate base
        conda.exe build recipe -m .ci_support\%CONFIG%.yaml
      displayName: Build recipe
      failOnStderr: false
      env:
        
        PYTHONUNBUFFERED: 1

    - script: |
        upload_package .\ .\recipe .ci_support\%CONFIG%.yaml
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      condition: not(eq(variables['UPLOAD_PACKAGES'], 'False'))

