# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win_vs2015
  pool:
    vmImage: vs2015-win2012r2
  timeoutInMinutes: 240
  strategy:
    maxParallel: 4
    matrix:
      win_c_compilervs2015cxx_compilervs2015vc14:
        CONFIG: win_c_compilervs2015cxx_compilervs2015vc14
        CONDA_BLD_PATH: D:\\bld\\
        UPLOAD_PACKAGES: False
        CONDA: D:\\Miniconda3\\
  steps:
    - script: |
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
  
    - powershell: |
        Write-Host "##vso[task.prependpath]C:\ProgramData\chocolatey\bin"
      displayName: Add choco to PATH

    # TODO: Fast finish on azure pipelines?
    - script: |
        ECHO ON
        choco install miniconda3 --params="'/D:D:\Miniconda3 /InstallationType:AllUsers'" --yes

    # Cygwin's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    # - script: rmdir C:\cygwin /s /q
    #   continueOnError: true

    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.6 conda-build conda conda-forge::conda-forge-ci-setup=2' # Optional
        installOptions: "-c conda-forge"
        updateConda: false
      displayName: Install conda-build and activate environment

    - script: set PYTHONUNBUFFERED=1

    # Configure the VM
    - script: setup_conda_rc .\ .\recipe .\.ci_support\%CONFIG%.yaml
    
    # Configure the VM.
    - script: |
        run_conda_forge_build_setup

      displayName: conda-forge build setup

    - script: |
        conda.exe build recipe -m .ci_support\%CONFIG%.yaml --debug
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1

    - script: |
        upload_package .\ .\recipe .ci_support\%CONFIG%.yaml
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      condition: not(eq(variables['UPLOAD_PACKAGES'], 'False'))
